### ISSUE TITLE
Minor typo in one reference 

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [audio-captioning/audio-captioning-papers#1]
J. Naranjo-Alcaza, S. Perez-Castanos, P. Zuccarello, and M. Cobos, "Task 6 DCASE 2020: Listen Carefully and Tell: An Audio Captioning System Based on Residual Learning and Gammatone Audio Representation," DCASE2020 Challenge, Tech. Rep., Jun. 2020

should be

**J. Naranjo-Alcazar**, S. Perez-Castanos, P. Zuccarello, and M. Cobos, "Task 6 DCASE 2020: Listen Carefully and Tell: An Audio Captioning System Based on Residual Learning and Gammatone Audio Representation," DCASE2020 Challenge, Tech. Rep., Jun. 2020

Anyway, many thanks for creating this repo and making easier to follow the of state-of-the-art of audio captioning

**Comment by dr-costas** [comment]
Thank you for spotting it! I will fix it right away, sorry for this.
